"""Static media metadata used by the public renderer."""
MEDIA_TYPES = {
    "movies": {
        "label": "Movies",
        "csv": "data/movies.csv",
        "watchlist_csv": "data/movies_watchlist.csv",
        "columns": [
            "Movie",
            "Date Watched/Rated",
            "Date Released",
            "Rating",
            "Director",
        ],
        "title_column": "Movie",
        "user_fields": ["Rating"],
        "auto_fields": ["Date Watched/Rated"],
        "api_fields": ["Date Released", "Director"],
        "provider": "tmdb_movie",
        "enabled": True,
    },
    "books": {
        "label": "Books",
        "csv": "data/books.csv",
        "watchlist_csv": "data/books_watchlist.csv",
        "columns": [
            "Book",
            "Date Read/Rated",
            "Date Published",
            "Rating",
            "Author",
        ],
        "title_column": "Book",
        "user_fields": ["Rating"],
        "auto_fields": ["Date Read/Rated"],
        "api_fields": ["Date Published", "Author"],
        "provider": "openlibrary",
        "enabled": True,
    },
    "tv": {
        "label": "TV Shows",
        "csv": "data/tv.csv",
        "watchlist_csv": "data/tv_watchlist.csv",
        "columns": [
            "Show",
            "Date Watched/Rated",
            "Date Premiered",
            "Rating",
            "Creator",
        ],
        "title_column": "Show",
        "user_fields": ["Rating"],
        "auto_fields": ["Date Watched/Rated"],
        "api_fields": ["Date Premiered", "Creator"],
        "provider": "tmdb_tv",
        "enabled": True,
    },
}
